### ISSUE TITLE
Failed to compile LosGatos project

### ISSUE THREAD

**Issue by rusty02** [davidortinau/LosGatos#7]
Error: Severity	Code	Description	Project	File	Line	Suppression State Error	NU1102	Unable to find package Xamarin.CommunityToolkit with version (>= 1.0.0-preview1093)
I tried to install the nuget package using command Install-Package Xamarin.CommunityToolkit -Version 1.0.0-pre4 but it still failed to compile. What version of Xamarin.CommunityToolkit do I need? I could not find any version >= 1.0.0-preview1093

**Comment by davidortinau** [comment]
Add the XCT nightly feed to your NuGet sources and make sure that is installed. We'll add a nuget.config to the source here also.

https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json

lmk if that doesn't resolve it for you.
